### ISSUE TITLE
Error running extract_patched_point

### ISSUE THREAD

**Issue by kaibagley** [DPIRD-FSI/extractOz#13]
Hey Adam,
I tried running through the README, and when I reach `extract_patched_point`, I get an error:

> Error in `[.data.table`(data.table::rbindlist(purrr::map(.x = silo_stations$station_code,  : 
>  Item 1 of j is 4 which is outside the column number range [1,ncol=0]

Haven't looked into the function yet so  unsure of why this might be caused.

This is the code I used:

>  three_sites <-
>      extract_patched_point(
>          x = locs,
>          start_date = "2021-01-01",
>          end_date = "2021-01-31",
>          api_key = Sys.getenv("DPIRD_API_KEY")
>      )

**Comment by adamhsparks** [comment]
Hi Kai,
can you provide any other details, a reprex? I'm able to reknit the whole Rmd file without error, _e.g._, https://github.com/DPIRD-FSI/extractOz/commit/21617be060a39a4835a9707d2fffe0d194eb6e9c

**Comment by adamhsparks** [comment]
Follow up, what versions of {extractOz} and {weatherOz} are you using? I suspect you might need to update your installed version(s).

**Comment by kaibagley** [comment]
R 4.3.1
weatherOz_0.0.1.9000
extractOz_1.0.0.9000

Reprex:
```
library(extractOz)
library(weatherOz)

locs <- list(
    "Merredin" = c(x = 118.28, y = -31.48),
    "Corrigin" = c(x = 117.87, y = -32.33),
    "Tamworth" = c(x = 150.84, y = -31.07)
)

zones <- extract_ae_zone(x = locs)

sorder <- extract_daas_soil_order(x = locs)

three_sites <-
    extract_patched_point(
        x = locs,
        start_date = "2021-01-01",
        end_date = "2021-01-31",
        api_key = Sys.getenv("DPIRD_API_KEY")
    )

```

**Comment by adamhsparks** [comment]
Hi @kaibagley, are you perchance using Windows?

@bozaah and I have managed to reproduce this but only on Windows computers, not on any Mac that we've tried (yet).

**Comment by kaibagley** [comment]
Yes I'm using Windows 10, maybe time to ask IT for a Linux laptop..

**Comment by adamhsparks** [comment]
I won't discourage that. 😂

But regardless, it's a bug that we need to fix. I think it's actually in {weatherOz} but shows up here.

**Comment by adamhsparks** [comment]
Hello, Kai!

I think I've tracked down the bug (2X) in {weatherOz} that was manifesting here in {extractOz}. The README.md is know one that was knit on a Windows laptop to ensure that everything works. Can you please try again and let me know if this is fixed?

You will need to update your {weatherOz} installation from GitHub to get the newest version. There are some small changes in this package as well.

**Comment by kaibagley** [comment]
Whole README works with no problems now, thanks alot for the quick work Adam!
