### ISSUE TITLE
This repository still uses my PATs

### ISSUE THREAD

**Issue by adamhsparks** [DPIRD-FSI/extractOz#19]
As I'm no longer the maintainer, I'd prefer it to not use my PATs for tic updates and other GH actions.

The tic updates will expire in 6 days, so I've deleted it. You will need to create a new token.

**Comment by bozaah** [comment]
Thanks Adam. I have updated the deploy keys and the two tic secrets too. Should be working ok now.

**Comment by bozaah** [comment]
Also just updated the code coverage secret and it runs successfully!
